theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
deployment:
  targets:
    - name: "production"
      URL: "s3://a3e3bc44ebeb3b3deab2b30e5c68f97a65beaccb80746784e4f41e103cecfea8?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
params:
  plausible: aliceaupaysdescryptos.org
  logo:
    header: "/assets/images/alice.png"
  summary:
    position: hero
  image_sizes:
    design_system:
      lightbox: 
        disabled: true
