theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
deployment:
  targets:
    - name: "production"
      URL: "s3://758fda1998d701ad3f8bfa3a22b53475bedc9a3501c4323f657b256d0939db7d?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"
params:
  plausible: aliceaupaysdescryptos.org
  logo:
    header: "/assets/images/alice.png"
  summary:
    position: hero
  image_sizes:
    design_system:
      lightbox: 
        disabled: true
